name: Deploy the backend
on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy to VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.233.193.198 -t "
            sudo docker stop Generate-AI-backend || true;
            sudo docker rm Generate-AI-backend || true;
            sudo docker pull pratham59/generate-ai-backend:latest;
            sudo docker run -d -p 8080:8080 \
              -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
              -e FAL_API_KEY='${{ secrets.FAL_API_KEY }}' \
              -e WEBHOOK_URL='${{ secrets.WEBHOOK_URL }}' \
              -e ACCESS_KEY_ID='${{ secrets.ACCESS_KEY_ID }}' \
              -e SECRET_ACCESS_KEY='${{ secrets.SECRET_ACCESS_KEY }}' \
              -e BUCKET_NAME='${{ secrets.BUCKET_NAME }}' \
              -e END_POINT='${{ secrets.END_POINT }}' \
              -e CLIENT_ID='${{ secrets.CLIENT_ID }}' \
              -e CLIENT_SECRET='${{ secrets.CLIENT_SECRET }}' \
              -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
              --name Generate-AI-backend pratham59/generate-ai-backend:latest;
          "   